const action_header = 'auth/';

// Types
export default {
  CREATE_APPOINMENT: action_header + 'CREATE_APPOINMENT',
  CREATE_APPOINMENT_SUCCESS: action_header + 'CREATE_APPOINMENT_SUCCESS',
  CREATE_APPOINMENT_FAILED: action_header + 'CREATE_APPOINMENT_FAILED',

  GET_APPOINMENT_BY_DAY: action_header + 'GET_APPOINMENT_BY_DAY',
  GET_APPOINMENT_BY_DAY_SUCCESS: action_header + 'GET_APPOINMENT_BY_DAY_SUCCESS',
  GET_APPOINMENT_BY_DAY_FAILED: action_header + 'GET_APPOINMENT_BY_DAY_FAILED',

  UPDATE_APPOINMENT: action_header + 'UPDATE_APPOINMENT',
  UPDATE_APPOINMENT_SUCCESS: action_header + 'UPDATE_APPOINMENT_SUCCESS',
  UPDATE_APPOINMENT_FAILED: action_header + 'UPDATE_APPOINMENT_FAILED',

  DELETE_APPOINMENT: action_header + 'DELETE_APPOINMENT',
  DELETE_APPOINMENT_SUCCESS: action_header + 'DELETE_APPOINMENT_SUCCESS',
  DELETE_APPOINMENT_FAILED: action_header + 'DELETE_APPOINMENT_FAILED',

  GET_EMPLOYEES: action_header + 'GET_EMPLOYEES',
  GET_EMPLOYEES_SUCCESS: action_header + 'GET_EMPLOYEES_SUCCESS',
  GET_EMPLOYEES_FAILED: action_header + 'GET_EMPLOYEES_FAILED',

  SELECT_SLOT: action_header + 'SELECT_SLOT',

  GET_ALL_SERVICES: action_header + 'GET_ALL_SERVICES',
  GET_ALL_SERVICES_SUCCESS: action_header + 'GET_ALL_SERVICES_SUCCESS',
  GET_ALL_SERVICES_FAILED: action_header + 'GET_ALL_SERVICES_FAILED',
};
